version: "3"
services:
  node-gulp:
    image: alpine:latest
    volumes:
      - ./www:/code
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "3000:3000"

  nginx-h3:
    image: wacdis/nginx:latest
    volumes:
      - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
      - ./letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./www:/code
      - ./logs:/var/log/nginx
      - ./www.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    network:
      - internal


  # PHP 8
  php8:
    image: wacdis/php:8.1.1
    volumes:
      - ./www:/code
    ports:
      - '9000'
    network:
      - internal

network:
  - internal