version: "3.9"
name: workspace
services:
  gulp-1:
    image: alpine:latest
    # container_name: gulp
    volumes:
      - ../__projects:/projects
      - ../__code:/code
    networks:
      bridged:
    network_mode: "bridge"
    ports:
      - "80:80"
      - "443:443"
      - "5522:22"
    command:
      - /bin/ash
      - -c
      - |
        apk update
        apk upgrade
        apk add openssh openrc nodejs npm
        npm install -g gulp-cli
        cd /projects/__
        npm install --save-dev gulp del gulp-autoprefixer autoprefixer gulp-file-include gulp-sass gulp-uglify uglify-js pump gulp-watch yargs
        tail -f /dev/null
networks:
  bridged: