version: "3"
services:
  node-gulp:
    image: alpine:latest
    volumes:
      - ./www:/code
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "3000:3000"
  nginx:
    image: wacdis/nginx-quic:latest
    volumes:
      - ./cert:/cert
      - ./manager:/code
      - ./www/dest:/code/dest
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      internal:
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443/tcp"
      - "443:443/udp"
      - "8443:8443/tcp"
      - "8443:8443/udp"
  php:
    image: wacdis/php:8.1.11-fpm-alpine3.16
    volumes:
      - ./manager:/code
      - ./www/dest:/code/dest
    networks:
      internal:
    ports:
      - "9000"

networks:
  internal: