version: "3"
services:


  # NGINX HTTP3 QUIC
  nginx-h3:
    image: wacdis/nginx:latest
    volumes:
      - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
      - ./letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./www:/code
      - ./logs:/var/log/nginx
      - ./www.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"


  # PHP 8
  php8:
    image: wacdis/php:8.1.1
    volumes:
      - ./www:/code
    ports:
      - '9000:9000'


  # MYSQL 8
  mysql8:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: divakovstartuper


  # CERTBOT
  certbot-nginx:
    image: nginx:alpine
    volumes:
      - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
      - ./letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./letsencrypt/www:/code
      - ./letsencrypt/logs:/var/log/nginx
      - ./letsencrypt/letsencrypt.conf:/etc/nginx/conf.d/default.conf
    networks:
      certbot-core:
    ports:
      - "80:80"
  certbot-reg:
    image: certbot/certbot
    networks:
      certbot-core:
    volumes:
      - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
      - ./letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./letsencrypt/www:/var/www/html/
    command: certonly --webroot -w /var/www/html/ -n --agree-tos -m hostmaster@esestas.com -d esestas.com -d www.esestas.com -d admin.esestas.com -d api.esestas.com -d files.esestas.com
  certbot-upd:
    image: certbot/certbot
    networks:
      certbot-core:
    volumes:
      - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
      - ./letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./letsencrypt/www:/var/www/html/
    command: certonly --webroot -w /var/www/html/ -n --agree-tos --renew-by-default -m hostmaster@esestas.com -d esestas.com -d www.esestas.com -d admin.esestas.com -d api.esestas.com -d files.esestas.com
  

  # SELENIUM


  # REDIS
  redis:
    image: redis:alpine
    command: redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: 'divakovstartuper'
    volumes:
      - './redis:/data:rw'
      - './redis.conf:/etc/redis.conf'
    ports:
      - '6379:6379'


  # RABBITMQ


  # ADMINER
  adminer:
    image: adminer:4.7.7-standalone
    ports:
      - '8080:8080'
